version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Download architect
          command: |
            curl -fsSL https://github.com/giantswarm/architect/releases/download/v2.1.0/architect-v2.1.0-linux-amd64.tar.gz | tar -xzv --strip-components 1 '*/architect'
            ./architect version
      - run:
          name: Deploy
          command: |
            ./architect deploy

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
