version: 2.1
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run: |
        ./architect version

    - deploy:
        command: |
          ./architect deploy

workflows:
  version: 2
  build:
    jobs:
      - build
