api_version: generators.giantswarm.io/v1
app_catalog: control-plane-catalog
app_destination_namespace: giantswarm
app_name: cluster-api-core
app_version: 0.3.22-gs6-crd
kind: Konfigure
metadata:
  annotations:
    config.kubernetes.io/function: |-
      exec:
        path: /plugins/konfigure
  name: cluster-api-core
name: cluster-api-core
