apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: cluster-api
  namespace: argocd
spec:
  destination:
    namespace: giantswarm
    server: https://kubernetes.default.svc
  project: collections
  source:
    path: .
    plugin:
      env:
      - name: KONFIGURE_APP_NAME
        value: cluster-api
      - name: KONFIGURE_APP_VERSION
        value: 0.3.0-alpha.9-175afaee912040e21c5e6bb66cb15059483e06f3
      - name: KONFIGURE_APP_CATALOG
        value: control-plane-test-catalog
      name: konfigure
    repoURL: https://github.com/giantswarm/config.git
    targetRevision: v1
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
