apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: releases-aws
  namespace: argocd
spec:
  destination:
    namespace: giantswarm
    server: https://kubernetes.default.svc
  project: collections
  source:
    path: .
    plugin:
      env:
      - name: KONFIGURE_APP_NAME
        value: releases-aws
      - name: KONFIGURE_APP_VERSION
        value: 0.0.0-4da6cec78c88eab36449b78df53762fc8dadb946
      - name: KONFIGURE_APP_CATALOG
        value: releases
      name: konfigure
    repoURL: https://github.com/giantswarm/config.git
    targetRevision: v1
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
