api_version: generators.giantswarm.io/v1
app_catalog: releases
app_destination_namespace: giantswarm
app_name: releases-aws
app_version: 0.0.0-4da6cec78c88eab36449b78df53762fc8dadb946
kind: Konfigure
metadata:
  annotations:
    config.kubernetes.io/function: |-
      exec:
        path: /plugins/konfigure
  name: releases-aws
name: releases-aws
