apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: releases-aws
  namespace: argocd
spec:
  destination:
    namespace: giantswarm
    server: https://kubernetes.default.svc
  project: collections
  source:
    path: .
    plugin:
      env:
      - name: KONFIGURE_APP_NAME
        value: releases-aws
      - name: KONFIGURE_APP_VERSION
        value: 0.0.0-d3ab469fefb412d5981732d6fc1a38d5a24a6b15
      - name: KONFIGURE_APP_CATALOG
        value: releases
      name: konfigure
    repoURL: https://github.com/giantswarm/config.git
    targetRevision: v1
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
