apiVersion: application.giantswarm.io/v1alpha1
kind: AppCatalog
metadata:
  labels:
    app-operator.giantswarm.io/version: 1.0.0
  name: control-plane-catalog
spec:
  config:
    configMap:
      namespace: draughtsman
      name: draughtsman-values-configmap
    secret:
      namespace: draughtsman
      name: draughtsman-values-secret
  description: 'App Catalog for Control Plane apps releases.'
  storage:
    URL: https://giantswarm.github.com/control-plane-catalog/
    type: helm
  title: Control Plane Catalog
