apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  creationTimestamp: null
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: vertical-pod-autoscaler-app-unique
  namespace: giantswarm
spec:
  catalog: control-plane-test-catalog
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: vertical-pod-autoscaler-app
  namespace: giantswarm
  userConfig:
    configMap:
      name: vertical-pod-autoscaler
      namespace: giantswarm
    secret:
      name: ""
      namespace: ""
  version: 0.0.0-719a0ace103ac5199db965c4a1e11ca381fc690d
status:
  appVersion: ""
  release:
    lastDeployed: null
    status: ""
  version: ""
